name: Node.js CI

on:
  push:
    branches: [ "pre-prod" ]
  pull_request:
    branches: [ "pre-prod" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
